apiVersion: v1
kind: Service
metadata:
  name: memo-api-service
spec:
  # ğŸ‘‡ typeì´ LoadBalancerë¡œ ë˜ì–´ ìˆëŠ”ì§€ í™•ì¸
  type: LoadBalancer
  selector:
    app: memo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080